### ISSUE TITLE
Test rust based web servers

### ISSUE THREAD

**Issue by jake-g00dwin** [Personal-Data-Acquisition/PDA_UI#1]
- [x] Build a repo to hold UI + webserver.
- [x] Build example branch with rust rocket
- [x] Build example branch with actix-web
- [x] Build example branch with tide
- [x] Research other Rust based webservers.

**Comment by jake-g00dwin** [comment]
Have the rocket rust web server example functional. If you want to give it a try just follow the README.md instructions.

**Comment by BlakeBabb** [comment]
Got the actix-web example up and running.

**Comment by BlakeBabb** [comment]
I feel like it's pretty well established at this point that we'll be using Rocket
